FROM golang:1.24-alpine

WORKDIR /app
COPY server/go.mod server/go.sum ./
RUN go mod download

COPY server/ .
RUN go build -o /usr/local/bin/pingo-server .

COPY tests/docker-turn/peer_test.go ./cmd/peer-test/main.go
RUN go build -o /usr/local/bin/peer-test ./cmd/peer-test/main.go

CMD ["/usr/local/bin/pingo-server"]
