import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle Push Notifications
self.addEventListener('push', (event) => {
    console.log('[SW] Push received:', event);
    let data = {};
    try {
        data = event.data ? event.data.json() : {};
    } catch (e) {
        console.error('Push event data is not JSON:', e);
        data = { title: 'Pingo', body: event.data ? event.data.text() : 'Alguien te está buscando.' };
    }

    const title = data.title || 'Pingo!';
    const options = {
        body: data.body || 'Toca para ver la ubicación.',
        icon: 'https://cdn-icons-png.flaticon.com/512/1865/1865269.png',
        badge: 'https://cdn-icons-png.flaticon.com/512/1865/1865269.png',
        vibrate: [100, 50, 100],
        data: {
            url: data.url || '/'
        },
        actions: [
            { action: 'open', title: 'Ver Mapa' }
        ]
    };

    event.waitUntil(
        self.registration.showNotification(title, options)
    );

    // Update App Badge if supported
    if ('setAppBadge' in navigator) {
        navigator.setAppBadge(1).catch((error) => {
            console.error('Error setting app badge:', error);
        });
    }
});

// Handle Periodic Background Sync (Heartbeat)
self.addEventListener('periodicsync', (event) => {
    if (event.tag === 'pingo-heartbeat') {
        console.log('[SW] Periodic Sync Heartbeat triggered');
        // We could do a background location fetch or connectivity check here
        // if the browser allows it (usually requires PWA installed and UI interaction)
    }
});

// Handle Messages from Clients
self.addEventListener('message', (event) => {
    console.log('[SW] Message received from client:', event.data);
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

// Broadcast to all clients
async function broadcastToClients(message) {
    const allClients = await clients.matchAll({ type: 'window' });
    for (const client of allClients) {
        client.postMessage(message);
    }
}

// Handle Notification Click
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    const urlToOpen = event.notification.data.url;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // If a window is already open, focus it and navigate
            for (let client of windowClients) {
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            // Otherwise, open a new window
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen);
            }
        })
    );

    // Clear App Badge when any notification is clicked
    if ('clearAppBadge' in navigator) {
        navigator.clearAppBadge().catch((error) => {
            console.error('Error clearing app badge:', error);
        });
    }
});

// Handle Web Share Target
self.addEventListener('fetch', (event) => {
    const url = new URL(event.request.url);
    if (event.request.method === 'POST' && url.pathname.includes('_share-target')) {
        event.respondWith((async () => {
            try {
                const formData = await event.request.formData();
                const file = formData.get('file');
                
                if (file) {
                    await new Promise((resolve, reject) => {
                        const request = indexedDB.open('pingo-share', 1);
                        request.onupgradeneeded = (e) => {
                            e.target.result.createObjectStore('files');
                        };
                        request.onsuccess = (e) => {
                            const db = e.target.result;
                            const tx = db.transaction('files', 'readwrite');
                            tx.objectStore('files').put(file, 'shared-file');
                            tx.oncomplete = () => resolve();
                            tx.onerror = () => reject(tx.error);
                        };
                        request.onerror = () => reject(request.error);
                    });
                }
                
                // Response.redirect REQUIRES an absolute URL string
                const redirectTarget = new URL('./?action=share_received', self.location.href).href;
                return Response.redirect(redirectTarget, 303);
            } catch (err) {
                console.error('[SW] Error handling share target:', err);
                const errorTarget = new URL('./?action=share_error', self.location.href).href;
                return Response.redirect(errorTarget, 303);
            }
        })());
    }
});

